server:
  port: 8093
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: C##dev
    password: minhaSenhaSegura123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
