spring:
  application:
    name: Banco de dados de Test para validação-
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev
    username: developer
    password: developer
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
     ddl-auto: create-drop
     show-sql: true

